stages:
  - deploy
#  - test

#test:
#  image: cypress/base:10
#  stage: test
#  script:
    # install dependencies
#    - npm install
    # start the server in the background
#    - npm run start &
    # run Cypress test in load balancing mode
#    - npm run cypress:run
  # artifacts:
  #   when: always
  #   paths:
  #     - cypress/videos/**/*.mp4
  #     - cypress/screenshots/**/*.png
  #   expire_in: 1 day

deploy dev:
  stage: deploy
  script:
    - ENVIRONMENT="dev"
    - APPLICATION="interaction-design-ui"
    - REMOTE_FOLDER="/var/www/html/$ENVIRONMENT/$APPLICATION"
    - REMOTE_SERVICE_OWNER="gitlab-runner"
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./package-lock.json
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./node_modules
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./dist
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S npm install
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S ng build --base-href ./ --configuration=$ENVIRONMENT
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S mkdir -p $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S cp -rf ./dist/* $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
  environment: development
  only:
    - dev
  when: manual

deploy test:
  stage: deploy
  script:
    - ENVIRONMENT="test"
    - APPLICATION="interaction-design-ui"
    - REMOTE_FOLDER="/var/www/html/$ENVIRONMENT/$APPLICATION"
    - REMOTE_SERVICE_OWNER="gitlab-runnerv"
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./package-lock.json
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./node_modules
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./dist
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S npm install
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S ng build --base-href ./ --configuration=$ENVIRONMENT
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S mkdir -p $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S cp -rf ./dist/* $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
  environment: development
  only:
    - test
  when: manual

deploy prod:
  stage: deploy
  script:
    - ENVIRONMENT="prod"
    - APPLICATION="interaction-design-ui"
    - REMOTE_FOLDER="/var/www/html/$ENVIRONMENT/$APPLICATION"
    - REMOTE_SERVICE_OWNER="gitlab-runner"
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./package-lock.json
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./node_modules
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S rm -rf ./dist
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S npm install
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S ng build --base-href / --configuration=$ENVIRONMENT
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S mkdir -p $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S cp -rf ./dist/* $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
  environment: development
  only:
    - main
  when: manual
